version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # Install Trivy
      - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
      - echo "deb https://aquasecurity.github.io/trivy-repo/deb generic main" | tee -a /etc/apt/sources.list
      - apt-get update && apt-get install -y trivy
      
      # Install OWASP Dependency Check
      - wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
      - unzip dependency-check-8.4.0-release.zip
      
      # Install SonarScanner
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip
      - unzip sonar-scanner-cli-4.8.0.2856-linux.zip
      - export PATH=$PATH:$(pwd)/sonar-scanner-4.8.0.2856-linux/bin

  pre_build:
    commands:
      - echo Security scanning started on `date`
      - npm install

  build:
    commands:
      # OWASP Dependency Check
      - echo "Running OWASP Dependency Check..."
      - ./dependency-check/bin/dependency-check.sh --project "sample-app" --scan . --format HTML --out . --outputFileName dependency-check-report || echo "OWASP scan failed but continuing"
      
      # Trivy filesystem scan
      - echo "Running Trivy filesystem scan..."
      - trivy fs --format table --output trivy-fs-report.html . || echo "Trivy scan failed but continuing"
      
      # SonarQube analysis
      - echo "Running SonarQube analysis..."
      - |
        sonar-scanner \
          -Dsonar.projectKey=sample-app \
          -Dsonar.sources=. \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_TOKEN \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info || echo "SonarQube analysis failed but continuing"

  post_build:
    commands:
      - echo Security scanning completed on `date`
      - echo "Checking generated files..."
      - ls -la
      - echo "Looking for OWASP report..."
      - find . -name "*.html" -type f
      - echo "Uploading security reports to S3..."
      
      # Upload reports to S3
      - TIMESTAMP=$(date +%Y%m%d-%H%M%S)
      - |
        if [ -f "dependency-check-report.html" ]; then
          echo "Found OWASP report, uploading..."
          aws s3 cp dependency-check-report.html s3://$SECURITY_REPORTS_BUCKET/owasp/$TIMESTAMP-owasp-report.html || echo "Failed to upload OWASP HTML report"
        else
          echo "OWASP report not found"
        fi
      - |
        if [ -f "trivy-fs-report.html" ]; then
          echo "Found Trivy report, uploading..."
          aws s3 cp trivy-fs-report.html s3://$SECURITY_REPORTS_BUCKET/trivy/$TIMESTAMP-trivy-fs-report.html || echo "Failed to upload Trivy HTML report"
        else
          echo "Trivy report not found"
        fi
      
      - echo "Security reports processing completed"

artifacts:
  files:
    - dependency-check-report.html
    - trivy-fs-report.html
  name: security-reports